version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.unified
    ports:
      - "80:80"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
      - ALLOWED_HOSTS=localhost,127.0.0.1,${DOMAIN:-yourdomain.com}
      - CORS_ALLOWED_ORIGINS=http://localhost,https://${DOMAIN:-yourdomain.com}
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
    restart: unless-stopped
