# Nixpacks configuration for Railway
# This tells Railway how to build and deploy your full-stack app

[phases.setup]
nixPkgs = ["nodejs", "python39", "pip"]

[phases.install]
cmds = [
  "cd frontend && npm ci",
  "cd backend && pip install -r requirements.txt"
]

[phases.build] 
cmds = [
  "cd frontend && npm run build",
  "cd backend && python manage.py collectstatic --noinput"
]

[phases.start]
cmd = "cd backend && python manage.py runserver 0.0.0.0:$PORT"
