# Nixpacks configuration for Railway
# This tells Railway how to build and deploy your full-stack app

[phases.setup]
nixPkgs = ["nodejs", "python39", "pip"]

[phases.install]
cmds = [
  "npm install --prefix frontend",
  "pip install -r backend/requirements.txt"
]

[phases.build] 
cmds = [
  "npm run build --prefix frontend"
]

[phases.start]
cmd = "python railway_start.py"
